version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kanakku_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kanakku
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - kanakku_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: kanakku_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - kanakku_network

volumes:
  postgres_data:


networks:
  kanakku_network:
    driver: bridge
